### ISSUE TITLE
项目导出pdf报错

### ISSUE THREAD

**Issue by anmei02** [condorheroblog/vuepress-plugin#18]
项目导出pdf报错

◆ Generating  ██████████████████████████████ 0/0
The website has no pages, please check whether the export path is set correctlyWaiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

**Comment by condorheroblog** [comment]
请提供更多信息或者在线连接：

1. 本地启动服务浏览器打开是否正常
2. 通过 `press-export-pdf info` 导出项目信息
3. 等等
