### ISSUE TITLE
npm run export-pdf没有报错但是本地没有pdf文件生成

### ISSUE THREAD

**Issue by AhZoey** [condorheroblog/vuepress-plugin#19]
执行过程
1.  npm install @condorhero/vuepress-plugin-export-pdf-v2 -D
2. pageage.json 
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/a1db4656-4df8-4346-a355-48bc35e27196)

4. 执行npm run export-pdf,结果如下
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/fc5d9c6c-9e05-455c-b108-e7a677f0d391)
所有的配置都是默认的，没有写配置文件

**Comment by condorheroblog** [comment]
这是 Windows 系统下的一个 bug，在 Core 
目录中使用了 join 方法进行路径拼接，而底层依赖的 fast-glob 只支持 Linux 风格的路径，导致读取不到文件，无法进行 PDF 合成。

```js
const tempPdfDir = join(tempDir, "pdf");
```

---

公司裁员了，我电脑交了，等我找到新工作有电脑了在修这个 bug💪

**Comment by condorheroblog** [comment]
已经在 v3.0.3 中修复
