### ISSUE TITLE
Error: Expected compressed object stream

### ISSUE THREAD

**Issue by AhZoey** [condorheroblog/vuepress-plugin#20]
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/8bf0ad03-2a2a-458c-a456-45eba4d214fe)
配置文件
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/160eba29-357c-422e-9af1-d7b0ccc5279b)
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/1cf31d8c-d036-44d1-bb80-05e35f554544)

**Comment by condorheroblog** [comment]
I didn't reproduce it, you can use latest Node.js and retry it.

**Comment by AhZoey** [comment]
node version :21.7.2
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/2dcfeca5-ccf1-4fbe-99e0-e3b2d8d77940)

npm fund 
![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/33896601/eb9c6118-a92c-4e14-9315-8829cd2ca788)

**Comment by condorheroblog** [comment]
Sorry, I use your config, but I don't repeat it. It's a weird bug for [pdfjs](https://github.com/rkusa/pdfjs), if you want to fix it that you can try it.

![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/47056890/77fc19f9-5ba8-45f6-8105-6452329cbc33)
