### ISSUE TITLE
Navigation on left side of every page

### ISSUE THREAD

**Issue by syou4you** [condorheroblog/vuepress-plugin#21]
Hi,

even if I use the example vuepress-next I get an output pdf with a navigation on the left of every page.

![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/162098899/2d8a72a9-2d24-4a76-81a6-07d6a94a4da2)

**Comment by condorheroblog** [comment]
Sorry, I can not repeat it.You can retry it using latest code.

![image](https://github.com/condorheroblog/vuepress-plugin-export-pdf/assets/47056890/6d0b3603-e259-44c7-b5b9-bd07fe281fcd)
