### ISSUE TITLE
SyntaxError: The requested module 'vuepress' does not provide an export named 'defaultTheme'

### ISSUE THREAD

**Issue by garyee** [condorheroblog/vuepress-plugin#22]
Hi,

no matter what I am doing I get the error
`SyntaxError: The requested module 'vuepress' does not provide an export named 'defaultTheme'` when running npm install on my vuepress project.
I have tried NodeJs in the versions 16,20 and 22 everytime I get the same error.
My package.json looks like:
```
"dependencies": {
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@condorhero/vuepress-plugin-export-pdf-v2": "^2.0.1",
    "@vuepress/bundler-webpack": "^2.0.0-rc.13",
    "@vuepress/plugin-register-components": "^2.0.0-rc.34",
    "@vuepress/plugin-search": "^2.0.0-rc.34",
    "@vuepress/theme-default": "^2.0.0-rc.33",
    "sass": "^1.77.4",
    "sass-loader": "^14.2.1",
    "vuepress": "^2.0.0-rc.13",
    "yaml": "^1.10.0"}
```

**Comment by condorheroblog** [comment]
Hello, Please in install the latest version of @condorhero/vuepress-plugin-export-pdf-v2(v3.0.3 now) and retry.

I notice you are using the old version.

**Comment by garyee** [comment]
It did work!
I had do to a little detour because I got:
```
file://..../node_modules/@vuepress/plugin-git/node_modules/execa/lib/utils/max-listeners.js:1
import {addAbortListener} from 'node:events';
        ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadUserConfig (file:///..../node_modules/@vuepress/cli/dist/index.js:77:18)
    at async CAC.serverApp (file:///..../node_modules/@condorhero/vuepress-plugin-export-pdf-v2/dist/shared/vuepress-plugin-export-pdf-v2.564f7dfd.mjs:136:42)
```
Which I do only state here for documentation purposes.
The Reason for this error is that "node:events" only works for the NodeJs version >= 16.9 ([source](https://stackoverflow.com/questions/75985086/error-cannot-find-module-nodeevents-on-render-discord-js-v-14))
For me I had to go for NodeJs 18 in order for the error to go away

Thank you.

**Comment by condorheroblog** [comment]
Excellent.
