### ISSUE TITLE
Order of pages in PDF

### ISSUE THREAD

**Issue by syou4you** [condorheroblog/vuepress-plugin#23]
Hi condorhero, 
I want to export my PDF with the pages in the order of a given array. 
I tried it as described in the README but the order was according to the folder structure.
Should it work for version 2?

**Comment by condorheroblog** [comment]
Of course.

There is a `sorter` function that you can sort you page's router.

https://github.com/condorheroblog/vitepress-export-pdf/blob/90d50e772274937b1cba4a6d3a3ff5a25d62cebe/examples/vitepress-docs/docs/.vitepress/vitepress-pdf.config.ts#L56-L60

Maybe followed link below can help you.

https://github.com/condorheroblog/vitepress-export-pdf/issues/12
