### ISSUE TITLE
Config file `routePatterns` option not working

### ISSUE THREAD

**Issue by ginnsx** [condorheroblog/vuepress-plugin#24]
我使用的是 vuepress-plugin-export-pdf-v2，配置了 `routePatterns` 来排除一些文件：
```ts
 routePatterns: ["!/", "!/zh-tw/**", "!/en/**"],
```
但没有生效。
我试着 debug 了一下，发现在 `serverApp.ts` 第 106 行，将 pages 转换为 `hasePages` 时为每个 path 拼接了前缀，导致与 `routePatterns` 不匹配，因而在 core 包下 `generatePdf.ts` 执行 `filterRoute` 时过滤失败。

目前我需要将配置改为下面的格式才有效：
```ts
routePatterns: ["!/aposd2e-zh/", "!/aposd2e-zh/404.html", "!/aposd2e-zh/zh-tw/**", "!/aposd2e-zh/en/**"],
```

感觉可以保留原来的 path 用于过滤，或者为 routePatterns 也拼接相同的前缀。

Thanks for your work~

**Comment by condorheroblog** [comment]
我都是在 sorter 函数里面打印出来页面路径，然后在去过滤。

```js
  sorter: (pageA, pageB) => {
    console.log(pageA);
    const aIndex = routeOrder.findIndex(route => route === pageA.path)
    const bIndex = routeOrder.findIndex(route => route === pageB.path)
    return aIndex - bIndex
  }
 ```
