### ISSUE TITLE
导出来的pdf除了首页，全是404的页面

### ISSUE THREAD

**Issue by sunnysteam** [condorheroblog/vuepress-plugin#25]
![image](https://github.com/user-attachments/assets/281d482f-5c6b-4162-94b9-12012c73ca2f)

**Comment by condorheroblog** [comment]
请提供更多软件版本信息

**Comment by sunnysteam** [comment]
"vuepress": "^2.0.0-rc.7",
"@condorhero/vuepress-plugin-export-pdf-v2": "^3.0.3",

除了首页，其他页面导出来都是404的页面，但是页面的数量是正确的
@condorheroblog

**Comment by condorheroblog** [comment]
无法复现，你本地 dev 打开试试链接是不是正常的，或者提供一个仓库我看看。

**Comment by Isaaczhr** [comment]
遇到了相同的问题，这是我的仓库: https://github.com/Isaaczhr/NcatBotDocs

运行命令 npm run export-pdf 生成的页面除了首页其余全是404页面，如图：

![Image](https://github.com/user-attachments/assets/e4376d5c-bf18-4d90-a238-6539a63e8d1c)

猜测可能是读取路由出错了
