### ISSUE TITLE
SyntaxError: Named export 'context' not found. The requested module 'esbuild' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by itmier** [condorheroblog/vuepress-plugin#26]
![image](https://github.com/user-attachments/assets/c4dd65f4-4624-49e5-9721-5c6476df0e96)
node版本： v18.5.0 | v18.20.4 | v20.16.0
window: win10
package: "@condorhero/vuepress-plugin-export-pdf": "^3.0.3"
执行 npm run export-pdf

**Comment by condorheroblog** [comment]
你在 `package.json` 中加下 `"type": "module",` 强制使用 ESModule。
