### ISSUE TITLE
How can I zoom in on the table to show the full content?

### ISSUE THREAD

**Issue by ykla** [condorheroblog/vuepress-plugin#3]
There are many tables in <https://handbook.bsdcn.org/FreeBSD-Handbook-CN.pdf> that are not fully displayed, such as the "Glossary of Terms" on pages 54-59. The original article is available at <https://handbook.bsdcn.org/yi-zhe-shuo-ming.html>. How can I zoom in on the table to show the full content? Thanks a lot. Now index.scss is:

```
blockquote > p {
  display: block;
  margin-block-start: 1em;
  margin-block-end: 1em;
  margin-inline-start: 0px;
  margin-inline-end: 0px;
}
div.theme-default-content:not(.custom) {
    max-width: 75%;
}
@media print {
  .navbar,
  .sidebar,
  .sidebar-mask,
  .page-edit,
  .page-nav {
    display: none;
  }
}
```

![QQ图片20220922140326](https://user-images.githubusercontent.com/10327999/191670157-64dcab30-bf5d-45bc-9493-6e88c7bd50eb.png)
![QQ图片20220922140330](https://user-images.githubusercontent.com/10327999/191670163-b293a613-fb7f-40fc-8458-f3564a8e0c39.png)

**Comment by condorheroblog** [comment]
Two solutions:

1. add a class name for table(`glossary-table`) and then:

```css
@media print {
	.glossary-table {
		zoom: .5;
	}
}
```

![image](https://user-images.githubusercontent.com/47056890/191687856-2586d9f7-36aa-497e-8eea-a529ec91b917.png)

2. change print pdf size:

```js
{
	pdfOptions: {
		format: "A0" // default A4
	}
}
```

[format doc](https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.lowercasepaperformat.md)

**Comment by ykla** [comment]
OK, Thank you, and I solved the problem. The reason is that the program does not do line breaks for website links, so whenever a line contains a link, it will overflow the screen. Just write the link in markdown syntax "[text]\(link)" to solve the problem. The amount of text does not affect the display of the table.
