### ISSUE TITLE
the pdf I exported is an empty file

### ISSUE THREAD

**Issue by lll4770** [condorheroblog/vuepress-plugin#6]
I used vuepress-plugin-export-pdf-v2 to export pdf, after installing this plugin, I run "npm run docs:build" command, it showed me the error "cannot find module node_modules\vuepress-shared\lib\client.js". Can you help?

**Comment by condorheroblog** [comment]
Check the version of VuePress. The `vuepress-plugin-export-pdf-v2` corresponds to `VuePress2.x`. If there is any problem, please paste the code.

**Comment by lll4770** [comment]
Thanks, I re-install VuePress, it works.
BTW, this plugin seems not to export the site navbar menu to the PDF index. I don't know I just ask if we can read the "sidebar.ts" to generate the PDF index, and if we can generate the index, maybe we can also modify the static links(I saw all the internal links in the pdf file pointed to the localhost site html pages)

**Comment by condorheroblog** [comment]
You should be talking about the PDF outline. I have studied this direction for a long time, but there is still a headache that cannot be solved. When a long HTML is generated into a PDF, I cannot get how many parts of the page are truncated.

So the function of generating outline is to be determined. If you are interested, you can also study and welcome technical exchanges.

**Comment by condorheroblog** [comment]
> I don't know I just ask if we can read the "sidebar.ts" to generate the PDF index, and if we can generate the index, maybe we can also modify the static links(I saw all the internal links in the pdf file pointed to the localhost site html pages)

Hi @lll4770 

Now I have already solved this problem, This review is a good guide to getting started - https://github.com/condorheroblog/vuepress-plugin-export-pdf/issues/5#issuecomment-1528836983
